### ISSUE TITLE
How to deploy a gremlin server with Unipop

### ISSUE THREAD

**Issue by jiangyifangh** [unipop-graph/unipop#36]
I am working on a project that require graph queries on ElasticSearch and I found Unipop which fits our use case perfectly. Well done!
However, I found few clues about how to set up a gremlin server with unipop. The unipop-elastic2 is half developed. I found that I could not even package unipop-elastic successfully.
It would be very helpful if you could give any advice. I am really looking forward to the release of a stable version.

**Comment by paul-k-civitas** [comment]
Has there been any update on this? I'm also looking to use Gremlin with Elasticsearch, and this project is very promising. Is it possible someone could throw together a quick description of how it works, how to use it, and what work needs to be done to get this over the line to a stable release?

**Comment by rmagen** [comment]
Hey Paul,

Unfortunately I had to stop working on this project because of a change of work place. @seanbarzilay still contributes sometimes, and I also heard from my previous employer that they want to re-ignite the project.

If you or someone else wants to contribute I'd be more than happy! Also calling on @okram and @spmallette . I'm not up to date on the Tinkerpop scene, but maybe there are people in the community who would find this project interesting, and help it gain traction.

As for what needs to be done.. The system works pretty well, the current tests seem to be passing, so a stable release isn't far off. There are a few areas that could use some work:

- Documentation - basically detailing the things you asked about :) This includes:
  - Setting up Unipop as Console/Server/Embedded (pretty standard Tinkerpop stuff)
  - Defining Schemas - mapping data sources to a graph ontology (there are a few examples in the tests).
  - Extending Unipop with Controllers (data sources) & Schemas (data virtualization).
- Tests – We use the TestSuites supplied with Tinkerpop, which we run with different configurations. I think the tests cover most of what we need in the code, but we could use more configurations to test out more use cases, especially those integrating different data sources, which are a bit lacking. 
- Performance - there are many possible optimizations that we can add, this usually involves implementing some kind of TraversalStrategy.
- Data Sources - we currently implemented Controllers for JDBC, Elastic-Search, and REST. More can be added.
- Schemas (“data virtualization” layer) – more can be done here to simplify and support more use cases.

If someone is interested in working on this, I can write down some basic documentation on how things work, and can break it down to more detailed Github issues.

**Comment by jim-snyder-civitaslearning** [comment]
@rmagen We (my current employer) are going to give a serious attempt to push this effort forward because it fits some use cases for us pretty nicely -- Specifically ElasticSearch. Two things

1. The basic docs would help (what ever you can spare).
2) Any contacts we can find that would help us decide if we should fork this code or contribute (we are open to either option). If others want to collaborate to finish this, we are open.

**Comment by seanbarzilay** [comment]
@jim-snyder-civitaslearning I will be working on the documentation of the project and probably deploy it to maven finally in the next week or so

**Comment by goelrajat** [comment]
Hi,
I am also interested in the documentation of the project. Also, I had a query regarding the same. From the README file, it is mentioned that "you get the benefits of a graph data model without migrating/replicating/restructuring your data, whether its stored in a RDBMS, NoSql Store, or any other data source". 
I have a ElasticSearch index where the index has schema like User1, User2, Emails Sent, Emails Received. I wanted a graph model query on this data where in Vertices are all distinct Users from either User1 or User 2 fields. Edges are edges between users who have either sent or received email to each other i.e. either Emails Sent or Emails Received > 0.
How can I do the same?

**Comment by seanbarzilay** [comment]
Hi,
I am currently working on the documentation of the project and I'm expected
to finish it in a few days, and I will have a section specifically on
mapping to existing data stores.

If you have any questions after I post the documentation I will gladly help
you.

**Comment by seanbarzilay** [comment]
Most of the user documentation is finished you can check it out in our wiki
[Setup Gremlin Server](https://github.com/unipop-graph/unipop/wiki/Setup-Gremlin-Server)
